# DO NOT EDIT THIS FILE!
#
# Python module MONITORMANAGERINTEGRATIONSERVICE__POA generated by omniidl

import omniORB
omniORB.updateModule("MONITORMANAGERINTEGRATIONSERVICE__POA")

# ** 1. Stub files contributing to this module
import MONITORMANAGERINTEGRATIONSERVICE_idl

# ** 2. Sub-modules

# ** 3. End
