package MONITORMANAGERINTEGRATIONSERVICE;


/**
* MONITORMANAGERINTEGRATIONSERVICE/MonitorManagerIntegrationService_ifce.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MONITORMANAGERINTEGRATIONSERVICE.idl
* Thursday, September 9, 2021 2:20:16 PM UTC
*/

public interface MonitorManagerIntegrationService_ifce extends MonitorManagerIntegrationService_ifceOperations, DCF.Device_ifce, org.omg.CORBA.portable.IDLEntity 
{
} // interface MonitorManagerIntegrationService_ifce
