package MONITORMANAGERINTEGRATIONSERVICE;

/**
* MONITORMANAGERINTEGRATIONSERVICE/MonitorManagerIntegrationService_ifceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MONITORMANAGERINTEGRATIONSERVICE.idl
* Thursday, September 9, 2021 2:20:16 PM UTC
*/

public final class MonitorManagerIntegrationService_ifceHolder implements org.omg.CORBA.portable.Streamable
{
  public MONITORMANAGERINTEGRATIONSERVICE.MonitorManagerIntegrationService_ifce value = null;

  public MonitorManagerIntegrationService_ifceHolder ()
  {
  }

  public MonitorManagerIntegrationService_ifceHolder (MONITORMANAGERINTEGRATIONSERVICE.MonitorManagerIntegrationService_ifce initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MONITORMANAGERINTEGRATIONSERVICE.MonitorManagerIntegrationService_ifceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MONITORMANAGERINTEGRATIONSERVICE.MonitorManagerIntegrationService_ifceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MONITORMANAGERINTEGRATIONSERVICE.MonitorManagerIntegrationService_ifceHelper.type ();
  }

}
