package MONITORMANAGERINTEGRATIONSERVICE;


/**
* MONITORMANAGERINTEGRATIONSERVICE/MonitorManagerIntegrationService_ifceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MONITORMANAGERINTEGRATIONSERVICE.idl
* Thursday, September 9, 2021 2:20:16 PM UTC
*/

public interface MonitorManagerIntegrationService_ifceOperations  extends DCF.Device_ifceOperations
{

  // Configurable attributes (device properties)
  String monitorsConfigurationPath ();

  // Configurable attributes (device properties)
  void monitorsConfigurationPath (String newMonitorsConfigurationPath);
} // interface MonitorManagerIntegrationService_ifceOperations
